---
- set_fact: logstash_nodename={{ role_path | basename }}
- include_role:
    name: _predeploy
- include_role:
    name: _logstash_prerequisite
  with_items:
    - logstash-codec-netflow
    - logstash-filter-dns
    - logstash-filter-translate
- include_role:
    name: _logstash_copyfiles
  with_items:
    - conf.d/netflow_cdn/proto.yml
    - conf.d/netflow_cdn/src_dst_port.yml
    - conf.d/netflow_cdn/tcp_flags.yml

- name: Deploy | [{{ logstash_nodename }}] - Generate Logstash Node Config
  vars:
    netflow_cdn: "{{ node_vars.netflow_cdn | default({'inputs':{},'outputs':[]}) }}"
    logstash_rest_api_port: "{{ netflow_cdn.inputs.udp[0].port | int + 30000 }}"
    jmxremote_port: "{{ netflow_cdn.inputs.udp[0].port | int + 40000 }}"
  template:
    src: "{{ item }}"
    dest: "{{ logstash.nodes_root }}/{{ logstash_nodename }}/{{ item | regex_replace('[.]j2$', '') }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - cdn-netflow.json.j2
    - jvm.options.j2
    - logstash.yml.j2
    - conf.d/01-input.j2
    - conf.d/02-filter.j2
    - conf.d/03-output.j2
