---
- name: Generate tuned-network.service
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  with_items:
    - tuned-network.service.j2

- name: Ensure tuned-network is running and enabled as configured.
  systemd:
    name: tuned-network.service
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Refuse responding to broadcasts request
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    sysctl_set: yes
    reload: yes
  when: not container

- name: Enable TCP SYN Cookie Protection
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    sysctl_set: yes
    reload: yes
  when: not container

  #sudo tc  qdisc add dev eno1 root handle 1: mqprio
