---
- name: Build CDN IP list
  set_fact:
    cdn_ips: "{{ cdn_ips | default([]) + [lookup('dig', '%s/A' % (hostvars[item].inventory_hostname_short))] }}"
  with_items:
    - "{{ groups['all_cdn'] | default([]) }}"
    - "{{ groups['all_tb_cdn'] | default([]) }}"
  delegate_to: localhost
  run_once: True

- name: Ensure iptables persent
  apt:
    name: iptables
    state: present
    install_recommends: no

- name: Generate iptables-rules.servie
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename | regex_replace('\.j2$', '') }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  with_items:
    - iptables-rules.service.j2
    - firewall.sh.j2

- name: Ensure iptables-rules.service is running and enabled as configured.
  systemd:
    name: iptables-rules
    state: restarted
    daemon_reload: yes
    enabled: yes
