---
- name: Install related components and using openresolv
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - dnsutils
    - resolvconf

- name: stop systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Ensure resolvconf is running and enabled as configured.
  systemd:
    name: resolvconf
    state: started
    enabled: true

- name: Remove ifup program to push DNS to resolvconf
  replace:
    path: /etc/network/interfaces
    regexp: '(?<!#)dns-(nameservers|search|sortlist) '
    replace: '#dns-\1 '
    owner: root
    group: root
    mode: 0644

- name: Ensure /etc/resolvconf/resolv.conf.d/
  file: path=/etc/resolvconf/resolv.conf.d state=directory

- name: Reset resolvconf base
  copy:
    dest: /etc/resolvconf/resolv.conf.d/base
    content: ''
    force: yes
  notify:
    - 'regenerate resolv.conf'

- name: Set resolvconf original
  copy:
    src: original
    dest: /etc/resolvconf/resolv.conf.d/original
    force: yes
  notify:
    - 'regenerate resolv.conf'

- name: Link resolvconf original to tail
  file:
    src: /etc/resolvconf/resolv.conf.d/original
    dest: /etc/resolvconf/resolv.conf.d/tail
    force: yes
    state: link
  notify:
    - 'regenerate resolv.conf'

- name: Link /etc/resolv.conf to /run/resolvconf/resolv.conf
  file:
    src: /run/resolvconf/resolv.conf
    dest: /etc/resolv.conf
    force: yes
    state: link
  notify:
    - 'regenerate resolv.conf'

- name: Disable LLMNR
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^LLMNR='
    line: 'LLMNR=no'

- stat:
    path: /run/systemd/resolve/resolv.conf
  register: systemd_resolved_conf

- name: Link resolvconf original to tail
  file:
    src: /etc/resolv.conf
    dest: /run/systemd/resolve/resolv.conf
    force: yes
    state: link
  when: systemd_resolved_conf.stat.exists == True

- meta: flush_handlers
