---
- name: Ensure iptables persent
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - iptables
    - ipset

- name: Generate iptables-rules.servie
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename | regex_replace('[.]j2$', '') }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  with_fileglob:
    - templates/*.j2

- name: Ensure firewall.d directory
  file: path="/etc/systemd/system/firewall.d/" state=directory mode=0755 owner=root group=root

- name: Ensure iptables-rules.service is running and enabled as configured.
  systemd:
    name: iptables-rules
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: iptables tuning
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    sysctl_file: "{{ sysctl_custom_conf }}"
    state: present
  with_items:
    # netfilter
    - { name: net.netfilter.nf_conntrack_max, value: 10000000 }
    - { name: net.netfilter.nf_conntrack_tcp_loose, value: 0 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_established, value: 1800 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_close, value: 10 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_close_wait, value: 10 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_fin_wait, value: 20 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_last_ack, value: 20 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_syn_recv, value: 20 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_syn_sent, value: 20 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_time_wait, value: 10 }
