---
api_kong_gw:
  templatename: api-kong-gw
  inputs:
    udp:
      - host: 192.168.101.202
        port: 10519
      - host: 192.168.101.107
        port: 10519
    tcp:
      - host: 192.168.101.202
        port: 10519
      - host: 192.168.101.107
        port: 10519
  outputs:
    elasticsearch:
      host:
        - es-hk-eqx01-master-vip:9200
