---
network:
  templatename: network
  inputs:
    udp:
      - host: 0.0.0.0
        port: 10517
    tcp:
      - host: 0.0.0.0
        port: 10517
  outputs:
    - elasticsearch:
        id: log
        host:
          - eslog-hk-eqx01-01-data:9200
    # - elasticsearch:
    #     id: oi
    #     host:
    #       - esoi-hk-eqx01-01-data:9200
