---
httpguard:
  templatename: httpguard
  inputs:
    udp:
      - host: 192.168.101.202
        port: 10520
      - host: 192.168.101.108
        port: 10520
    tcp:
      - host: 192.168.101.202
        port: 10520
      - host: 192.168.101.108
        port: 10520
  outputs:
    elasticsearch:
      host:
        - es-hk-eqx01-master-vip:9200
