---
httpguard:
  templatename: httpguard
  inputs:
    udp:
      - host: 192.168.151.102
        port: 20516
    tcp:
      - host: 192.168.151.102
        port: 20516
  outputs:
    elasticsearch:
      host:
        - 192.168.151.101:9200
