---
- name: Stop softflowd
  systemd:
    name: softflowd.service
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: True

- name: Uninstall softflowd
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ base_root }}/bin/softflowd"
    - "{{ base_root }}/bin/softflowctl"
    - /etc/default/softflowd
    - /etc/systemd/system/softflowd.service
