---
- name: Copy logger
  copy:
    src: logger
    dest: "{{ base_root }}/bin"
    force: yes
    mode: 0755
    owner: root
    group: root

- name: Ensure nc persent
  apt:
    name: netcat-openbsd
    state: present
    install_recommends: no

- name: Generate heartbeat.timer and heartbeat.service
  vars:
    service_name: Server HeartBeat
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  with_items:
    - heartbeat.service.j2
    - heartbeat.timer.j2

- name: Ensure heartbeat is running and enabled as configured.
  systemd:
    name: heartbeat.timer
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: heartbeat_enabled
