---
- name: Network | Get Default interface
  shell: /sbin/ip route show | grep "^default" | sed "s|^.* dev \([^ \t]*\) .*$|\1|"
  register: def_iface_out
  changed_when: False

- name: Env | Get Root Physical Block Size
  shell: blockdev --getpbsz $(df | grep " /$" | cut -d" " -f1) 2>/dev/null || echo 512
  register: pbsz_out
  changed_when: False
#
# # lscpu or {{ ansible_processor_vcpus }} are unreliable in VPS, their value may be a vhost value
# - name: Env | Get CPU Count
#   shell: cat /proc/cpuinfo | grep processor | wc -l
#   register: cpucount_out
#   changed_when: False
#   tags: always

- name: Env | Get systemd version
  shell: systemd --version | head -n 1 | cut -d' ' -f2
  register: systemd_ver_out
  changed_when: False

# https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1496554.html
# https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=832713;filename=skip-seccomp.patch;msg=128
# https://github.com/systemd/systemd/issues/3882
- name: Env | Check seccomp capability
  shell: grep Seccomp /proc/self/status && echo 1 || echo 0
  register: is_seccomp_enabled_out
  changed_when: False

- set_fact:
    container:                     "{{ ansible_virtualization_role == 'guest' and
                                      (ansible_virtualization_type == 'openvz' or
                                       ansible_virtualization_type == 'lxc' or
                                       ansible_virtualization_type == 'docker') }}"

- set_fact:
    vm:                           "{{ ansible_virtualization_role == 'guest' and not container }}"
    physical_host:                "{{ ansible_virtualization_role == 'NA' and ansible_virtualization_type == 'NA' }}"
    region:                       "{{ inventory_hostname_short | regex_replace('(?:uat-)?cdn(?:-g\\d+)?-([^-]+)-\\d+$', '\\1')  }}"
    codename:                     "{{ ansible_distribution_release }}"
    systemd_service_mgr_version:  "{{ systemd_ver_out.stdout | int }}"
    is_seccomp_enabled:           "{{ is_seccomp_enabled_out.stdout | int == 1 }}"
    iface:                        "{{ def_iface_out.stdout }}"
    pbsz:                         "{{ pbsz_out.stdout | default(512) | int }}"
