---
access_log:
  templatename: ngx-access-cdn
  inputs:
    udp:
      - host: 192.168.151.102
        port: "{{ cdn.logstash.access_log.udp.port }}"
    tcp:
      - host: 192.168.151.102
        port: "{{ cdn.logstash.access_log.udp.port }}"
  outputs:
    elasticsearch:
      host:
        - 192.168.151.101:9200
error_log:
  templatename: ngx-error-cdn
  inputs:
    udp:
      - host: 192.168.151.102
        port: "{{ cdn.logstash.error_log.udp.port }}"
    tcp:
      - host: 192.168.151.102
        port: "{{ cdn.logstash.error_log.udp.port }}"
  outputs:
    elasticsearch:
      host:
        - 192.168.151.101:9200
