---
- set_fact: logstash_nodename={{ role_path | basename }}
- include_role:
    name: _predeploy
- include_role:
    name: _logstash_prerequisite
  with_items:
    - logstash-filter-dns
    - logstash-filter-cidr
    # - logstash-filter-tld
    - logstash-output-mongodb
    - logstash-codec-compress_spooler

- name: Deploy | [{{ logstash_nodename }}] - Generate Logstash Node Config
  vars:
    access: "{{ node_vars.access_log | default({'inputs':{},'outputs':{}}) }}"
    error: "{{ node_vars.error_log | default({'inputs':{},'outputs':{}}) }}"
    logstash_rest_api_port: "{{ access.inputs.udp[0].port | int + 30000 }}"
    jmxremote_port: "{{ access.inputs.udp[0].port | int + 40000 }}"
  template:
    src: "{{ item }}"
    dest: "{{ logstash.nodes_root }}/{{ logstash_nodename }}/{{ item | regex_replace('[.]j2$', '') }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - ngx-access-cdn.json.j2
    - ngx-error-cdn.json.j2
    - jvm.options.j2
    - logstash.yml.j2
    - conf.d/01-input.j2
    - conf.d/02-filter.j2
    - conf.d/03-output.j2
