---
- name: Generate tuned-network.service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  with_items:
    - { src: tuned-network.j2, dest: /etc/default/tuned-network }
    - { src: tuned-network.service.j2, dest: /etc/systemd/system/tuned-network.service }
  when: not container

- name: Ensure tuned-network is running and enabled as configured.
  systemd:
    name: "{{ item }}"
    state: "{{ container | ternary('stopped', 'restarted') }}"
    enabled: yes
    daemon_reload: yes
  with_items:
    - systemd-networkd
    - systemd-networkd-wait-online
    - tuned-network.service
  ignore_errors: True

- name: Refuse responding to broadcasts request
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    sysctl_set: yes
    reload: yes
  when: not container

- name: Enable TCP SYN Cookie Protection
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    sysctl_set: yes
    sysctl_file: "{{ sysctl_conf_file }}"
    reload: yes
  when: not container

  #sudo tc  qdisc add dev eno1 root handle 1: mqprio
