---
- name: Build CDN IP list
  set_fact:
    cdn_dns: "{{ cdn_dns | default([]) + [{'ip':lookup('dig', '%s/A' % (hostvars[item].inventory_hostname_short)), 'name': hostvars[item].inventory_hostname_short}] }}"
  with_items:
    - "{{ groups['all_cdn'] | default([]) }}"
    - "{{ groups['all_tb_cdn'] | default([]) }}"
  delegate_to: localhost
  run_once: True
